export const robots = [
  {
    id: 1,
    name: 'Amirhossein Arezaei',
    username: 'Amir',
    email: 'AmirhosseinArezaei@gmail.com',
    phone: 912456789,
  },
  {
    id: 2,
    name: 'Roya Saeedi',
    username: 'Roya',
    email: 'RoyaSaeedi@gmail.com',
    phone: 9127563458,
  },
  {
    id: 3,
    name: 'Khatere Saeedi',
    username: 'Khatere',
    email: 'KhatereSaeedi@gmail.com',
    phone: 9123458765,
  },
  {
    id: 4,
    name: 'Ali Arezaei',
    username: 'Ali',
    email: 'aliarezaei@gmail.com',
    phone: 9124563421,
  },
  {
    id: 5,
    name: 'Fahime Arezaei',
    username: 'Fahimeh',
    email: 'fahimearezaei@gmail.com',
    phone: 9126793465,
  },
  {
    id: 6,
    name: 'Nayereh Saeedi',
    username: 'Nayere',
    email: 'Nayeresaeedi@gmail.com',
    phone: 9129874567,
  },
  {
    id: 7,
    name: 'Adel Saeedi',
    username: 'Adel',
    email: 'adelSaeedi@gmail.com',
    phone: 9125462345,
  },
  {
    id: 8,
    name: 'Fatemeh Arezaei',
    username: 'Fatemeh',
    email: 'fatemearezaei@gmail.com',
    phone: 9126579087,
  },
  {
    id: 9,
    name: 'Morteza Arezaei',
    username: 'Morteza',
    email: 'mortezaarezaei@gmail.com',
    phone: 9124563456,
  },
  {
    id: 10,
    name: 'Niyayyesh Khalili',
    username: 'Niyayesh',
    email: 'niyayeshkhalili@gmail.com',
    phone: 9124567456,
  },
  {
    id: 11,
    name: 'Mahboobe Safaei',
    username: 'Mahboobbe',
    email: 'mahboobesafaei@gmail.com',
    phone: 9124556856,
  },
  {
    id: 12,
    name: 'Amirhossein Khalili',
    username: 'Amir2',
    email: 'amirhosseinkhalili@gmail.com',
    phone: 9124889456,
  }
];
